name: magicka_community_patch_installer_ui
description: Flutter Windows and Linux UI for the Magicka Community Patch installer.
publish_to: "none"
version: 0.0.49+49

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/payload/
    - assets/magicka-workshop-sidebar.png
    - assets/pjl234678.png
    - assets/PurpleHeartE54.png
    - assets/Sadness.jpg
    - assets/Skappnil.png
    - assets/bitesquid-mod-loader.jpg
  shaders:
    - shaders/flame_button.frag
    - shaders/install_star_button.frag
    - shaders/diamond_edge_star.frag
    - shaders/patreon_heart_flame.frag
    - shaders/patreon_fire_sparks.frag
